version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./to_say/.env
    ports:
      - 5432:5432
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
#  celery:
#    build: ./
#    command: celery -A to_say worker -l info
#    volumes:
#      - ./:/usr/src/to_say/
#    env_file:
#      - ./to_say/.env
#    depends_on:
#      - redis
volumes:
  postgres_data:
